n: 1000
k_con: 10
k_cat: 5
k_bin: 2
k_noise: 0
bad_ratio: 0.5
con_mean_bad_dif: 1
con_var_bad_dif: 0
con_nonlinear: 0.5
con_noise_var: 0.1
covars: null
iid: False
mixture: False
mix_mean_dif: null
mix_var_dif: null
cat_levels: 5
cat_nonlinear: 0
cat_var_share: 0.1
cat_noise_var: 0.1
bin_prob: 0.5
bin_mean_bad_dif: 0
bin_bad_ratio: 0.5
bin_mean_con_dif: 0
bin_var_bad_dif: 0
bin_noise_var: 0.1
encode_factors: False
verbose: True
seed: null
replicate: null